### ISSUE TITLE
Revival of deleted package: yatex

### ISSUE THREAD

**Issue by okayamat** [fink/fink-distributions#1138]
I would like to revive yatex, which was maintained by Todai Fink Team.
[yatex.patch](https://github.com/user-attachments/files/16040283/yatex.patch)
[yatex.txt](https://github.com/user-attachments/files/16040284/yatex.txt)
Tested on MacOS 10.14, 10.15 and 11.7.

**Comment by nieder** [comment]
@okayamat thank you for reviving this. Couple things to fix:
1) Use `Source-Checksum: SHA256(hash)` instead of `Source-MD5`. We're trying to get rid of Source-MD5.
2) Can you create a pull request with your submission? It'll make the merging easier.

The current package built for me on 10.14.6, but I don't use tex, so I can't test functionality, but I'm guessing you use it and it's OK.

**Comment by okayamat** [comment]
Thanks for your comment. Here is modified finkinfo:
[yatex.txt](https://github.com/user-attachments/files/16045033/yatex.txt)

On a pull request, I'm not sure how to push my commit... 

$ git push --set-upstream origin exp-okym
remote: Permission to fink/fink-distributions.git denied to okayamat.

**Comment by nieder** [comment]
For future pull, requests, you need to make a fork of this repository in your own github space and make the PR from there:
https://github.com/fink/fink-distributions/wiki/Submitting-new-or-updated-packages
