### ISSUE TITLE
Failed Install ghostscript-nox

### ISSUE THREAD

**Issue by sth0** [fink/fink-distributions#1198]
ghostscript-nox seems to build correctly but during the install I get the following error
```
While trying to install:
  ghostscript-nox-10.04.0-1

The following inconsistencies found:
  Unsatisfied dependency in groff: ghostscript

Trying to resolve dependencies...
Could not resolve inconsistent dependencies!
```
So ghostscript-nox needs groff which needs ghostscript that conflicts with ghostscript-nox?

Is this just a case that ghostscript-nox should provide "ghostscript"??  Or is there are deeper error.
macOS 15.2 / Xcode 16.2 but I don't think that matters.

**Comment by dmacks** [comment]
ghostscript-nox doesn't need groff, but the groff you have installed requires ghostscript (not the ghostscript-nox alternative). You can't install both types of ghostscript at the same time (they have the same executable name, etc). So fink isn't letting  you install ghostscript-nox because that would kick out ghostscript, which would break groff.

Conceptually, having ghostscript-nox provide ghostscript is the right idea. But the technical detail of 'provides' as is needed here doesn't work reliably here (would need to have both packages provide some other name, not one package provide the name of another actual package). Instead, groff can be updated to accept either ghostscript or ghostscript-nox. So as soon as you update your groff to that new release, you would be free to swap among the two ghostscripts. @nieder, any objection to making this tweak broadly across our remaining packages:
```
-[some sort of 'Depends' field]: ghostcript
+[some sort of 'Depends' field]: ghostcript | ghostscript-nox
```
Most other packages that require ghostscript already are marked to accept either one. The thinking seems to have been that packages that already require x themselves specified ghostscript (not -nox) purely because "the user has already chosen to have x, there's nothing extra being included here especially for ghostscript" (vs the -nox, whose main purpose was to have a thinner package without as many dependencies).

**Comment by nieder** [comment]
no reason that I know of to not have the two be swappable everywhere

**Comment by dmacks** [comment]
Not sure if this ticket is fully resolved, but the underlying issue I saw is fixed.

**Comment by sth0** [comment]
That seems to resolve my issue.  I was misled about it being a ghostscript issue but really a groff issue (and others) so I think this is good.
