### ISSUE TITLE
grep-3.1-1 needs standard gnulib fix

### ISSUE THREAD

**Issue by dmacks** [fink/fink-distributions#27]
Building on 10.13 fails self-test:

```
PASS: uniwidth/test-uc_width2.sh
../build-aux/test-driver: line 107: 71717 Illegal instruction: 4  "$@" > $log_file 2>&1
FAIL: test-vasnprintf
```

Fixed by the standard patch: [grep.patch](https://github.com/fink/fink-distributions/files/1594845/grep.patch.txt) (not sure why .patch isn't an accepted filetype, so I added a ".txt" extention to appease github)

**Comment by fingolfin** [comment]
Thanks, will look into it!

BTW, you also could have submitted this as a PR, then I'd just have reviewed and probably merged it (resp. "rebased" it) right away. But I am merely pointing that out, because for me (somebody who constantly uses GitHub and sometimes submits dozens of PRs a day), submitting a PR is more or less the same work as submitting an issue with an attached file; of course if it feels different for you, then an issue is perfectly fine, my intention is not to ask you to do my work for me :-)
