### ISSUE TITLE
perl5162-core fix for 10.14

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#290]
```
ln -s /usr/lib/libgcc_s.1.dylib /sw/lib/libgcc_s.10.4.dylib
```

fixes it and should be backwards safe.

in 10.12 /usr/lib/libgcc_s_.10.4.dylib is linked to /usr/lib/libgcc_s.1.dylib, and on 10.14 it no longer exists so recreating it fixes it.

**Comment by dmacks** [comment]
The underlying issue is that perl's build system hardcodes ```MACOSX_DEPLOYMENT_TARGET=10.3```, which triggers apple's linker to pass ```-lgcc_s_10.4``` implicitly. This setting is also what causes the tons of "ld: warning: object file (/usr/lib/bundle1.o) was built for newer OSX version (10.4) than being linked (10.3)" noise. The same setting is present in perl-5.18.2. Apple's build of system-perl removes the M_D_T flag in its system-perl builds on all fink supported platforms. Perl upstream has a more complex approach, which removes the flag but sometimes instead passes a modern compiler flag based on the actual local platform version (see https://rt.perl.org/Public/Bug/Display.html?id=128980).

We could remove the flag (and optionally use upstream's other flag) for 5.16.2, but that propagates a change into all compiled perlmods (binary difference in many -pm5162.deb). But as it stands, perl5162 doesn't build on 10.14 and is required for texi2html, a fairly important package.

TheSin's approach could work if we place it in the build dir and pass -L for it (and then remove that -L from the .deb so it doesn't propagate). We could backport upstream's fix and just ignore the binary .deb change. Or we could scrap perl5162 on recent 10.x altogether (Issue #6) and have texi2html include its own with whatever compile fixes (so there is no propagation and no need to continue generally supporting *-pm5162).

**Comment by dmacks** [comment]
It would be easy (I think) to put a libgcc_s symlink in the builddir and pass a local -L to it (then remove reference to it in the installed files so no %b residue propagates), like:
```
PatchScript: <<
 %{default_script}
 ln -s /usr/lib/libgcc_s.1.dylib libgcc_s.10.4.dylib
<<
CompileScript: <<
 sh Configure ... -Dldflags="-L%p/lib -L%b" ...
 make
<<
InstallScript: <<
 make install DESTDIR=%d
 perl -pi -e 's, -L%b,,g' %i/lib/perl5-core/5.16.2/darwin-thread-multi-2level/Config_heavy.pl
 ...
<<
```
I don't have a 10.14 to test that this correctly fixes the build, but I tested on 10.13 that the -L flag seems to be passed to the linker and is correctly scrubbed from the .deb.

However, due to the M_D_T=10.3 propagation, any compiled -pm5162 packages need some hack. Yuck, there is no clean solution.

**Comment by TheSin-** [comment]
This is no longer required with Xcode 10.1, the lib's_s.10.4.dylib is present and perl5162-core now builds.

**Comment by dmacks** [comment]
w00t, thanks for checking (and thanks Apple for fixing the goof).

**Comment by nieder** [comment]
However, there's now multiple current threads (early 2019) on the mailing lists with perl5162 breaking with 10.14/Xcode10.1 missing `-lgcc_s.10.4`.

Also, to keep these linked, see #339 for a patch that would still have the binary change issue with the perlmods.
