### ISSUE TITLE
extutils-makemaker fails tests looking for EXTERN.h

### ISSUE THREAD

**Issue by nieder** [fink/fink-distributions#355]
On 10.14/Xcode-CLI-10.1 with /usr/include missing:
````
#!/bin/bash -ev
export ARCHFLAGS=""
/usr/bin/make test || exit 2
PERL_DL_NONLAZY=1 "/usr/bin/arch" -x86_64 perl5.18 "-Iblib/arch" "-Iblib/lib" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00compile.t ............. ok
t/01perl_bugs.t ........... ok

#   Failed test '"make"   exited normally'
#   at lib/MakeMaker/Test/Setup/XS.pm line 441.
#          got: '512'
#     expected: '0'
# cp lib/XS/Test.pm blib/lib/XS/Test.pm
# Running Mkbootstrap for Test ()
# chmod 644 "Test.bs"
# "/usr/bin/perl5.18" -w -MExtUtils::Command::MM -e 'cp_nonempty' -- Test.bs blib/arch/auto/XS/Test/Test.bs 644
# "/usr/bin/perl5.18" -w "/System/Library/Perl/5.18/ExtUtils/xsubpp"  -typemap '/System/Library/Perl/5.18/ExtUtils/typemap' -typemap '/sw/build.build/extutils-makemaker-pm5182-7.34-1/ExtUtils-MakeMaker-7.34/t/XS-Testbasic/type map'  Test.xs > Test.xsc
# mv Test.xsc Test.c
# cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Os   -DVERSION=\"1.01\" -DXS_VERSION=\"1.01\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   Test.c
# Test.xs:1:10: fatal error: 'EXTERN.h' file not found
# #include "EXTERN.h"
#          ^~~~~~~~~~
# 1 error generated.
# make[1]: *** [Test.o] Error 1
````

**Comment by nieder** [comment]
Adding `xcrun --sdk` magic to ARCHFLAGS in InfoTest allows everything to pass.

**Comment by nieder** [comment]
ETA: extutils-parsexs-pm also fails with a missing EXTERN.h.

I notice that CompileScript sets ARCHFLAGS to have -I$SDK_PATH/usr/include, but this is not being set during TestScript. Should it be doing it there as well? @dmacks

**Comment by dmacks** [comment]
ARCHFLAGS is set on the commandline when calling Makefile.PL (to construct the Makefile):
````
ARCHFLAGS="..." ... perl... Makefile.PL ...
````
rather than being present in the CompileScript shell env. I no longer have any clue why it's implemented that way. But fink doesn't even pass it when calling 'make' in CompileScript. However, extutils-makemaker-pm.info has explicitly:
````
TestScript: <<
  #!/bin/bash -ev
  export ARCHFLAGS=""
  %{default_script}
<<
````

Packages that use Module::Build (instead of MakeMaker) pass it both to Build.PL and when calling the resulting ./Build but then not when running Build in any other phases.

It seems reasonable to set it in the env for all perl-versioned scripts if that works. Would sure simplify PkgVersion coding too. Instead of cloning the code in lots of the second-level branches of the get_script() spaghetti, just put it once in get_env().

**Comment by dmacks** [comment]
Ever since perl started building fat (32-bit + 64-bit) by default, we either needed to define ARCHFLAGS or use /usr/bin/arch to set a specific arch to make perl single-arch. Our default call of Makefile.PL uses /usr/bin/arch, which propagates into the constructed Makefile, so its recipes inherit it. But a few modules' t/ test scripts, including ExtUtils::MakeMaker, sublaunch other perl interps by calling $^X, which does not propagate env or arch. I added a ton of *-pm.patch years ago to insert /usr/bin/arch tweaks for the $^X calls (grep for 'byteorder'). However, extutils-makemaker-pmXXX does not use it (at t/lib/MakeMaker/Test/Setup/XS.pm line 134) so that package instead uses the ARCHFLAGS= in its .info TestScript to prevent multiarch.

I still don't have my 10.14 box available for fink. Does using that .patch method instead of ARCHFLAGS change the symptoms? Even if not, at least it would avoid overriding whatever ARCHFLAGS tricks fink decides to do in core.

**Comment by nieder** [comment]
@jwhowarth has what I think is a fix (untested here): https://github.com/jwhowarth/fink-distributions/commit/ff7207ff6d073c3d1358b35fb69e7cb28e5f1743

**Comment by nieder** [comment]
The jwhowarth fix also works on 10.14. I tried your byteorder suggestion but couldn't get my poor perl foo to make it work. Fixing the actual -I and -iwithsysroot inside the package seems more proper than shoehorning those flags at test time into ARCHFLAGS?

**Comment by nieder** [comment]
The jwhowarth fix also works on 10.14. I tried your byteorder suggestion but couldn't get my poor perl foo to make it work. 

I ran into various other perlmods that failed similarly (like module-build-pm) and they were all 'fixed' by adding `ARCHFLAGS=-I/SDK_PATH/PERL_HEADER` into TestScript. If a package explicitly blanks it, that's another issue but could be solved separately.

**Comment by danielj7** [comment]
Sorry, this should be fixed now on 10.14. I also updated to 7.36.

**Comment by danielj7** [comment]
Commit is https://github.com/fink/fink-distributions/commit/f631db87449a2036f6baedb3ebad862dc4b2be6b

**Comment by nieder** [comment]
Confirming extutils-makemaker-pm now builds. Thanks.
extutils-parsexs-pm still has the same problem.

**Comment by dmacks** [comment]
extutils-parsexs-pm is actually a bug in extutils-cbuilder-pm (compiler-driver using perl's own published compiler flags, which still only have top-level /System/Library/... even after apple instead buried that in the SDK subdir. Working on a fix......

**Comment by nieder** [comment]
@dmacks ping on the extutils-parsexs-pm via extutils-cbuilder-pm fix... ?
