### ISSUE TITLE
Update of gcc10 fails - Can't resolve dependency "xcode (>= 6.2)" for package "gcc10-10.3.0-1"

### ISSUE THREAD

**Issue by prehensilecode** [fink/fink-distributions#776]
- Fink package manager version 0.45.3
- Fink xcode.app version 12.4-1
- macOS 10.15.7
- XCode 12.4

Doing "fink update-all" gives:
```
Information about 11097 packages read in 1 seconds.
Can't resolve dependency "xcode (>= 6.2)" for package "gcc10-10.3.0-1" (no matching packages/versions found)
Exiting with failure.
```

Issue seems to be that fink/10.9-libcxx/stable/main/finkinfo/languages/gcc10.info refers to "xcode" rather than "xcode.app".

**Comment by akhansen** [comment]
Nope.  This is local to your system and is mostly Apple's fault.

Here's some background:

1. The _xcode_  virtual package dates from a time when Apple shipped the Xcode app and command-line tools in one package.  
2. When Apple separated the app from the command-line tools, we used _xcode_ to refer to the command-line tools because historically they was more important than the GUI.  _gcc10_ can be built completely without the Xcode app, so the use of the _xcode_ virtual package is correct.
3. In order to get a meaningful aggregate version for the command-line tools, we decided to use version information from the installer receipt for the Xcode Command Line Tools package.  This wasn't ideal, but it at least allowed us to check for minor and major updates in the Tools.
4. Within the past couple of years, things changed such that OS updates now essentially always remove the Xcode Command-Line Tools receipts, thus breaking the _xcode_ virtual package.

**Comment by akhansen** [comment]
Not a bug in this package, per se.

**Comment by prehensilecode** [comment]
This means that I would have to edit gcc10.info after every time I do "fink selfupdate". 

So: this is a predictable behavior for macOS, but the onus is now on the fink user to edit gcc10.info

**Comment by akhansen** [comment]
The other option is to reinstall the command-line tools.  That can be slightly more of a hassle than updating the .info file, but it's probably a more robust solution.

**Comment by akhansen** [comment]
I'll reopen this, perhaps to be spun off later.  At this point, an _xcode_ dependency really is kind of a bug, given the unreliability of the package detection mechanism

**Comment by dmacks** [comment]
@akhansen, and @nieder (who's wrangling other gcc things), any idea what actual xcode components are needed that entail having this dependency?

**Comment by TheSin-** [comment]
xcode is the devtools, and there are some issues with how the receipt for the clitools is processed you may need to do something like this

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

that will reinstall them and fix the receipt.

if you do `fink list xcode` and it's returning 0-0 then run what I posted to fix it.

**Comment by akhansen** [comment]
@dmacks No clue. Maybe some dev tools flakiness from way back then?  That's far enough back that maybe we should just make a distro-specific package description for whatever OS version still can use Xcode 6.2.  (10.9?)

**Comment by dmacks** [comment]
Offloading a special-case detail, such as BuildDepends for a subset of the Distributions, to its own .info is pretty standard, especially if it helps with supporting newer versions. https://xcodereleases.com/ indicates that xcode-6.2 is indeed 10.9.

**Comment by nieder** [comment]
I don't know why jwhowarth added a versioned xcode dependency to the gcc packages. In the 10.7 tree, gcc5 (latest there) required >= 4.6, and a versioned dependency goes back to at least 10.4. It might have been due to a specific flaky Xcode release way long ago, and then the dependency just got carried forward and updated as necessary.

Since 10.9 supports Xcode6, I feel we can probably remove the xcode CLT dependency across all the gccXX packages IFF it can build when only Xcode.app is present (none of my systems can currently do this at the moment). Removing the dependency doesn't fix Apple's messing with the receipts on a system update, but at least it will remove one irritation if Xcode.app is sufficient.

**Comment by akhansen** [comment]
My recollection is that the reason for this dependency was indeed specific flaky Xcode Command-line Tools.

I guess another option would be to use the "clang" virtual package instead, although there might have been cases in the early days where the command-line tools package version got bumped without changing the clang version.  

And/or for new enough OS we could scrap the receipt test for xcode and just check the clang version.  That currently tracks the command-line tools version pretty well.

**Comment by dmacks** [comment]
@nieder cleared out these deps via 2ea8593e402611381d57b1503b63b2436cf24aff
