### ISSUE TITLE
texinfo 6.8-700

### ISSUE THREAD

**Issue by TheSin-** [fink/fink-distributions#899]
on 11.2 at least I'm seeing this during bootstrap, and update and rebuild.  The age old EXTERN.h bug, but why it's it fatal.

make[1]: Leaving directory '/opt/sw/src/fink.build/texinfo-6.8-700/texinfo-6.8/tp/Texinfo/XS'
depbase=`echo TestXS.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I.  -I. -I./gnulib/lib -I./gnulib/lib -DDATADIR=\"/opt/sw/share\"  -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -DVERSION=\"0\" -DXS_VERSION=\"0\" -I/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE  -MT TestXS.lo -MD -MP -MF $depbase.Tpo -c -o TestXS.lo TestXS.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I. -I./gnulib/lib -I./gnulib/lib -DDATADIR=\"/opt/sw/share\" -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os -DVERSION=\"0\" -DXS_VERSION=\"0\" -I/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE -MT TestXS.lo -MD -MP -MF .deps/TestXS.Tpo -c TestXS.c  -fno-common -DPIC -o .libs/TestXS.o
TestXS.xs:4:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Makefile:1250: TestXS.lo] Error 1

**Comment by nieder** [comment]
Adding some variant of ``PERL_EXT_CPPFLAGS=-I`xcodebuild -version -sdk macosx10.15 Path`/System/Library/Perl/5.28/darwin-thread-multi-2level/CORE`` to %c finds system-perl::EXTERN.h, but then there's a dyld failure 
```
trying to call boot_TestXS...
  ...succeeded
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: ./.libs/TestXS.so
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: ./.libs/TestXS.so
  Expected in: flat namespace

checking whether we can build Perl extension (XS) modules... no
```
At least on 10.14.6, libperl.dylib from system-perl (5.18) doesn't have this symbol. It is present on fink-perl5282/5303, but not fink-perl5182. If I switch the build to use %p/bin/perl5.28.2, then I do get the XS modules built, but there's a test failure.

I don't think the error is fatal because the XS modules are optional.
Until we have a fink-perl that's available on all systems, I don't think we're going to solve this one :(

**Comment by dmacks** [comment]
Is there a switch (or hack we can write) to force disabling of the XS modules, so that everyone gets the same build product?

**Comment by nieder** [comment]
`--disable-perl-xs` seems to work here.

**Comment by TheSin-** [comment]
this seems to be fixed now?  I'm on 13.x and I have built texinfo

**Comment by nieder** [comment]
Probably, but unclear what fixed it. The last change to texinfo was only to get rid of varianted locale-textdomain-pm5XXX and unify all the dist-specific .info files.

**Comment by TheSin-** [comment]
Maybe it wasn't our change, maybe devtools change?  All I know is it's in my bootstrap and I have ran that like 20+ times in the last few days and it haven't failed yet ;)

**Comment by nieder** [comment]
Closing since it apparently now works.
